name = "tacops"
main = "worker/index.ts"
compatibility_date = "2026-08-12"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "tacops-analytics"
database_id = "b4e3ef6f-68c4-4622-b12b-93c90dc4c196"
